### ISSUE TITLE
sort skills in character sheet like in the PDF

### ISSUE THREAD

**Issue by stories-with-dice** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#101]
Hello,

Currently the skills in the Character sheet are sorted by row, not by column. This is confusing. It should be like in the PDF, to maintain compatibility and easier reading.

Compare

Foundry

![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/7314958/069074c0-096a-4897-8aeb-6387e2fb27cc)

PDF:

![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/7314958/1b797fb8-bacc-491a-ae4d-3992c700510c)

**Comment by 16-Bits** [comment]
I've got it sort of working on my own [fork ](https://github.com/16-Bits/delta-green-foundry-vtt-system) of the system but ran into graphical issues when hiding skills on the NPC sheet. I don't have a good understanding of how hiding the skills work and have been busy lately so I've been unable to develop it any further. Would appreciate it if someone could have a look and help me with it.
Player sheet example
![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/26033112/53c567cf-c866-4bd2-9c00-42178ff10556)
NPC sheet example
![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/26033112/0622d5e8-2498-47c7-bfa1-fbfeaaf5d28d)
NPC sheet with hidden skills
![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/26033112/e36e346f-8bf1-4af2-8667-ef581ea8ed4b)

**Comment by stories-with-dice** [comment]
That looks good to me! 

What is the graphical issue?

**Comment by jalensailin** [comment]
Hi! One of the devs here. Thanks for doing this work :). I think I have found a simpler solution that takes care of the graphical issue that you spoke of. it just requires a few lines change of code. ill be posting an MR soon. Let me know what you think

NPC - All Skills Shown: 
![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/72114365/2ea34b1e-9bd1-4fce-83d9-310c4c9db64a)

NPC - Skills Hidden:
![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/72114365/122c8e9d-eaa2-4b8b-a94e-79721d0898c8)

**Comment by 16-Bits** [comment]
Looks good to me, it's so much easier to find and read skills by just going down a column as opposed to rows
