### ISSUE TITLE
checkbox for Exhaustion

### ISSUE THREAD

**Issue by stories-with-dice** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#104]
Could you please add a checkbox somewhere in the actor sheet to keep track of Exhaustion? Optionally, maybe make it a `-10` or `-20` penalty to every roll, as per the rules?

**Comment by TheLastScrub** [comment]
Sorry for the delayed response on this, but hopefully better late than never. This should be in the next release, at this point just waiting on a little code review.

<img width="404" alt="image" src="https://github.com/user-attachments/assets/9fbc75b5-52ca-49e9-9b27-5db5dd4cc92d">

<img width="295" alt="image" src="https://github.com/user-attachments/assets/8701480c-075d-40d5-ac82-451b081b1269">

**Comment by TheLastScrub** [comment]
Should be in v1.4.6 when I package and release it.
