### ISSUE TITLE
Pregen Agents have Unarmed Combat as a Melee Weapon roll (instead of Hand to Hand)

### ISSUE THREAD

**Issue by wispborne** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#110]
I didn't check all pregens, but the ones that I did (eg ASENCIO, KIRBY) have an Unarmed Attack that rolls Melee Weapons, not Hand to Hand.

The Unarmed Attack in the compendium is correct, so players can delete the pregen attack and replace it with the compendium one.

**Comment by TheLastScrub** [comment]
Ahh yep, I see it, woops... Thanks, I will fix that and regenerate the compendium.
