### ISSUE TITLE
Pharmacy and Surgery 

### ISSUE THREAD

**Issue by LyonelMandrake** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#12]
Unless I am missing something, it looks as though Pharmacy and Surgery are missing from the skills list on the Actor sheet.

Thanks for making this BTW!

**Comment by TheLastScrub** [comment]
Huh can't believe I missed those two.  Should be easy to fix though.

**Comment by TheLastScrub** [comment]
Should be fixed in v0.9.4
