### ISSUE TITLE
Shotgun (Firing Shot) appears twice in Firearms compendium

### ISSUE THREAD

**Issue by andrewbeard** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#121]
<img width="313" alt="image" src="https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/15827939/07e607ba-e0ca-4250-af1b-885c84f1eb0a">

In the 1.4.5 the Shotgun (Firing Shot) entry appears twice in the Firearms list.

**Comment by andrewbeard** [comment]
It look likes there are to different files in the compendium that are _very_ similar but not identical. The second one seems to have a reference to the first, so I think the first (Zh1TVVNUFBxfxAOc) is the original.

https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/blob/master/packs/source/firearms/Shotgun__Firing_Shot__Zh1TVVNUFBxfxAOc.json
https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/blob/master/packs/source/firearms/Shotgun__Firing_Shot__ZyOe653MI3bPZwQ0.json

**Comment by TheLastScrub** [comment]
Should be in v1.4.6 when I package and release it.
