### ISSUE TITLE
[ENH] Show target number for Special Trainings on the character sheet

### ISSUE THREAD

**Issue by Vogliadicone** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#130]
As a player I would like to see the target number for a special training instead of the attribute (f.e. DEX: 60 or DEXx5: 60 instead of DEX - 11).
![Target-Number](https://github.com/user-attachments/assets/20699de3-e9dc-4fc9-a5fa-8147d2538365)
Right now the target number is shown for normal skills, custom skills and special skill trainings (f.e. Swim - 60). Just for special skill trainings with attributes it just shows the attribute number instead of the actual target number which is a bit confusing for new players ("I don't wanna try that, with just 11% my chances are fare too low").

And maybe use always a colon instead of a dash. Because the dash can be misinterpreted as an minus.

- Foundry 12.330
- Delta Green 1.4.6

**Comment by TheLastScrub** [comment]
This one is pretty easy, so went ahead and just did it quickly. I think the dash is pretty clear in this context, but I changed it to a comma like this instead:

![image](https://github.com/user-attachments/assets/5bc7f5c7-2fa8-4536-a7b0-dc4a3543969d)
