### ISSUE TITLE
Medium Pistol Damage

### ISSUE THREAD

**Issue by LyonelMandrake** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#14]
Currently set to 1d8 should be 1d10.  

Also, ammo seems to be set at 20 for many weapons (perhaps it was just a first pass thing).

Might be worthwhile to make two Medium Pistols (one semi-auto and one revolver) to account for the differing ammo ammounts.

**Comment by TheLastScrub** [comment]
Thanks for the bug report, I'll fix the damage on the pistol.  

Ammo is a whole different issue. Probably just needs reworked entirely at some point since magazine size, capacity and spare ammunition are all sort of expected to go in the same field at the moment.

**Comment by TheLastScrub** [comment]
Should be fixed in v0.9.4 (pistol damage anyways)
