### ISSUE TITLE
Support for Dice So Nice module

### ISSUE THREAD

**Issue by JiDW** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#15]
Hello!

I'm one of the author of the "Dice So Nice!" module (3D dice). One player of Delta Green reached out to me because we wasn't able to make 3D dice work with your system.

I took a quick look into your roll class and there's very little you would need to do if you wanted to support the Dice So Nice module.
You'll just need to attach the roll object and the ROLL type when you create your roll chat message.

We have a documentation for systems authors available here: https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/wikis/Integration#step-3-create-a-chat-message-with-the-required-data

If you wish to add this support and need help, please do not hesitate to contact me on Discord: JDW#6422

Sidenode: I've tried to install your system on 0.7.3 but I couldn't create an actor. Got `Error: Required field type not present in Actor.`

Regards.

**Comment by TheLastScrub** [comment]
Hey @JiDW , I quite like Dice So Nice for my PF2e and SF games, my DG game is on hiatus right now so I guess I never tried it with it for my own system haha... I did a quick test and as you said it was pretty easy to add it in for skill checks. So I'll see if I can add it for all other two roll types (damage and lethality) for the next release.

I _think_ the 'Required field' error is a bug with Foundry...  Someone else pinged me about it today, and when I dug in, the errors all seem to be in the Foundry code from what I can tell.  I see some chatter on the Discord server that seems like a similar issue from someone else: 

https://discordapp.com/channels/170995199584108546/670336275496042502/761490450804506644

It looks like Atropos released a patch that may have fixed the issue:

https://discordapp.com/channels/170995199584108546/760675730848743435/761380315720974386

I haven't tested installing the patch myself to see if it resolves the Actor issue though.

**Comment by TheLastScrub** [comment]
Yeah I think have damage and lethality updated as well.  So should be good to go once I package another release.  Next release should be soon, just trying to grind through adding in localization to everything after the fact...

**Comment by TheLastScrub** [comment]
Should be addressed in v0.9.4
