### ISSUE TITLE
Suggestion: Limited permission for an Agent sheet makes it so that player can only see the Portrait and the Physical description/Notes field

### ISSUE THREAD

**Issue by Albolynx** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#16]
A cool thing about the 5e system in Foundry is that Owner permission means full access, Observer means that the player can see everything but can't edit, and Limited permission means they can only see the portrait and biography (not stats, features, inventory etc) - making it ideal permission level for other player character sheets (so every player has some basic info about others but don't have extensive knowledge about their characters). I was wondering if something similar can't be done for Delta Green? Currently, Observer and Limited permissions seem to do the same.

Either way, thank you a lot for your work, I have been running Delta Green games for a couple weeks now and it works great!

**Comment by TheLastScrub** [comment]
Thanks for the feedback @Albolynx , it's always cool to hear people are using it and that it's working for their games. 

I think I see how the 5e sheet does this, interestingly enough it actually loads an entirely different file (e.g. character sheet) based on the launching user's permissions.  Shouldn't be too hard to do the same thing, and just show a stripped down version of the existing DG actor sheet.

As far as what should be shown to the limited user, should it just be the image, name/rank, profession and what is currently on the C.V. tab?  Something like this?

![image](https://user-images.githubusercontent.com/67403321/99217848-e1607880-278d-11eb-99ad-3efe29ae8c0b.png)

**Comment by Albolynx** [comment]
Yeah, the CV tab only would work! I hope it doesn't turn out too hard to implement - thank you for supporting this system!

**Comment by TheLastScrub** [comment]
No it was actually pretty easy, the change is pretty much already made.  Whenever I package the next version, it should be included.

**Comment by TheLastScrub** [comment]
Just released version 0.9.7 which should have this added in.  Let me know if you have any issues with it.  I'm going to close the issue for now, but feel free to open again if needed.
