### ISSUE TITLE
Suggestion: choose bonus or malus

### ISSUE THREAD

**Issue by Darshyne** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#17]
with a right click on a skill check you can choose +20% +40 or -20% -40% before roll.

**Comment by TheLastScrub** [comment]
I've been working on this a little bit already, should be ready in not too long

**Comment by TheLastScrub** [comment]
Just released version 0.9.7 which should have this added now.  You can right-click or shift click to get a dialogue to modify a roll.  It will work for all skill tests and for damage roll formula (for doubling weapon damage for instance).  I'm going to close the issue for this, feel free to open again if you have issues with it.
