### ISSUE TITLE
Typo in lang file en.json

### ISSUE THREAD

**Issue by roestrei** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#19]
Hey, thank you for making this system for foundry. We found a typo while playing but were able to modify the json file and fix it, wanted to give a heads up.

under **lang/en.json**, line 10 there's a typo for Alertness, the display value is "Alerness"

10 >     "DG.Skills.alertness": "Alterness",

Should be changed to "Alertness"

**Comment by TheLastScrub** [comment]
Thanks, I'll get that fixed

**Comment by TheLastScrub** [comment]
Just released version 0.9.7 which should have this fix in it.
