### ISSUE TITLE
Non-localized skill name when you click on weapon name

### ISSUE THREAD

**Issue by Phenomen** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#24]
1. Add weapon to agent.
2. Click on the weapon name.

In the chat card you will see non-localized skill name.

**Comment by TheLastScrub** [comment]
I think I found this one and fixed it (along with a related tooltip error).  So should be fixed in the next package.

![image](https://user-images.githubusercontent.com/67403321/111022847-461d8f80-838a-11eb-8049-e0ce57fa3a66.png)
