### ISSUE TITLE
"Damage" and "Lethality" are not bold in the chat cards

### ISSUE THREAD

**Issue by Phenomen** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#25]
All other skills and checks have a bolded emphasis of the term but when you roll weapon damage/lethality, those terms are not bolded.

**Comment by TheLastScrub** [comment]
I think this change has been made, hopefully in a way that doesn't mess up anyone's translation, but it is possible...

![image](https://user-images.githubusercontent.com/67403321/111023489-330cbe80-838e-11eb-8fdd-5830f7f34c5e.png)
