### ISSUE TITLE
Combat Enhancement:

### ISSUE THREAD

**Issue by CthulhuRol** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#30]
I don't know if it's a system issue or it's an improvement to implement in the future.

When I fight between two NPCs and have a hit on a weapon, I deal the damage but the damage is not automatically subtracted from the target sheet. I am using the spanish localization and I remember some lines regarding the messages about this kind of action during the combat, but then, it is not implemented. Maybe could be a problem with the localization. I didn´t check without that.

It would be extraordinary if this were automatically, subtracting the value of the target's armor from the damage points.

And at the same time, the armor piercing value of the weapon might subtract those points from the armor value.

**Comment by TheLastScrub** [comment]
This functionality hasn't been implemented yet.  Armor has a place for it's armor value, and weapons have a place to note penetration, so  I think this could be implemented as perhaps buttons in the chat cards, similar to how it is done in the Pathfinder 2e system.  I'd need to spend a bit of time on it though to come up with a good way to do it.

**Comment by TheLastScrub** [comment]
Because there isn't a lot of battle map use in DG, I can't really think of a good way to do this one since most solutions I've seen in other systems rely on having an actively selected token.  So I'm going to close this for now, but might re-open in the future if I can think of a good way to do it.
