### ISSUE TITLE
Suggestion: GM Roll Tickbox on rightclick

### ISSUE THREAD

**Issue by botais** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#33]
Considering things like optional secret SAN rolls and some GMs who like to keep Alertness or Search roll results secret, it would be cool if a rightclick on a stat or skills would allow you to tick a box for GM or blind rolls (same window where you can add bonuses).

**Comment by TheLastScrub** [comment]
I think this wouldn't be too hard to add.  Probably won't swing around to it until I've finished getting the changes in for 0.8.x complete however.

**Comment by TheLastScrub** [comment]
I didn't due a check box, but there should be a new dropdown with all the standard roll modes (per the chat box) in both roll dialogue windows now.  It will default to whatever is currently selected in the chat window, but will not override that setting.  Note you will need to be on the latest Foundry VTT version 0.8.6 or higher to pull this update.
