### ISSUE TITLE
No more character sheets with the new release (0.8.6)

### ISSUE THREAD

**Issue by Hrunh** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#34]
Hello mate,
First of all, thanks for this great system that allow me to play at this wonderful roleplaying game.

Then, the character sheet is no more available with the new 0.8.6 release of FoundryVTT.
The sheets of my world are no longer displayed, so I try to create a new world and the sheets, event if they are now dispayed, are empty, with no skills. 

When I try to update the system, i had the following error message: 
"the request to https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/raw/master/system.json did not provide a valid manifest file".

**Comment by TheLastScrub** [comment]
I don't have a 0.8.x compatible system written yet, but the changes the system needs is pretty much done.  Hopefully will publish the update this weekend.  But the 0.8.x update completely changed how character sheets work, so the old version of the system will NOT work with it.

**Comment by TheLastScrub** [comment]
I published the updated that should be compatible with 0.8.6 (AND ONLY 0.8.6+).  I think pulling the update should solve your issue so I'm going to close the issue.  But feel free to log a new one if it doesn't.
