### ISSUE TITLE
NPC Ritual Skill

### ISSUE THREAD

**Issue by thecodex101** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#37]
Hi, 

First love the sheet and improvments and it works great so thank you. 

The Ritual Skill on the NPC seems to be stuck as a default value of 49.? Am I missing something? 

Cheers

Ian

**Comment by TheLastScrub** [comment]
Hey @thecodex101, the Ritual skill currently works like the Ritual skill for the Agent type actor, that is to say it's calculated as [99-SAN].  So if it's working as intended, as you change the current SAN of the NPC the Ritual skill should automatically recalculate.  Is this not what you see?  I probably should have made the skill box not editable in hindsight...

![image](https://user-images.githubusercontent.com/67403321/129493775-b357275c-1a0a-478e-a448-2b3b891286f3.png)
