### ISSUE TITLE
Unarmed strike uses melee skill

### ISSUE THREAD

**Issue by HaleMorne** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#38]
I just noticed that by default unarmed strike in the hand-to-hand weapons compendium defaults to the melee weapon skill. Easy enough to fix on a character sheet, but thought you might want to know

**Comment by TheLastScrub** [comment]
Thanks, I'll get that fixed.

**Comment by TheLastScrub** [comment]
Sorry for the long delay, but I hope this is fixed now...
