### ISSUE TITLE
Moving the IS LETHAL checkmark to the inventory.

### ISSUE THREAD

**Issue by hydrated12** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#39]
As the title suggests, it would be way more convenient to have the Lethal/Normal damage toggle next to every weapon in the inventory, without having to open the edit item menu.

**Comment by TheLastScrub** [comment]
I may add this in the future, but for now I'll probably leave this as it is. One workaround if you frequently need to switch between the two modes is to just add the weapon twice to the Agent's sheet, once with normal damage and once with 'Lethal' checked off.

**Comment by jalensailin** [comment]
Here is how I would handle this. Let me know what you think. I can make a PR once my other one is approved. Once you get your v10 changes in, I can update this code for v10 as well. Again, no rush

![Lethality Toggle](https://user-images.githubusercontent.com/72114365/187836354-92615d40-bd1c-452e-a573-30dad3694bad.gif)

**Comment by TheLastScrub** [comment]
Should be resolved with v1.1.0.
