### ISSUE TITLE
Apply Damage no longer an option in combat - Resolved

### ISSUE THREAD

**Issue by HisBoySherman** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#40]
After updating from Foundry 0.8.7 to 0.8.8 the 'Apply Damage' pop-up no longer shows in chat when interacting with the damage roll result vs a targeted hostile.

I can replicate this in a new world with no modules active and with a fresh install of DG 0.9.9

**Comment by TheLastScrub** [comment]
I haven't ever had a 'Apply Damage' button in the system, so I think this must have been something in a module you were using.  It's possible something in the latest Foundry or Delta Green system update broke compatibility with the module.  I think I did make some changes to how the damage rolls were localized in the last round of updates.

**Comment by HisBoySherman** [comment]
I agree, that must have been it. Sorry for the trouble.
Should have got back to you sooner but our group has been playing a lot of DG. Thanks for all your hard work.

**Comment by TheLastScrub** [comment]
You're very welcome, sorry whatever happened broke the apply damage functionality.  Applying damage or SAN loss to a selected token is something I could look at in the future.  Just a little tricky due to most people not actually having a token on the canvas like you would with DnD or Pathfinder.
