### ISSUE TITLE
Keep SAN private?

### ISSUE THREAD

**Issue by cherojack** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#41]
This might be a little niche, but for Handlers who like using the "Keep SAN private" rule, would it be possible to accommodate that in the system? Either a toggle to default SAN rolls to Private GM roll, or keeping SAN rolls public but hiding the target on the chat window message would work, I think.

**Comment by TheLastScrub** [comment]
I think this change should be made in the latest release.  Just need to go into the system settings and enable it.
