### ISSUE TITLE
Sanity sticks at 99

### ISSUE THREAD

**Issue by E1GB** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#45]
Sanity does not correlate to POW, I have turned off the private san option and removed the world and system, issue persists

**Comment by TheLastScrub** [comment]
Can you give me an example of what you mean?  SAN only correlates to POW at character creation (i.e. starting SAN is equal to starting POWx5), and afterwards is not tied to it at all.  The only thing that affects it is the Unnatural skill, which lowers maximum SAN by that much from 99.

**Comment by E1GB** [comment]
Thanks for the response, I may well just be looking at this wrong.  The unnatural skill does lower the max san, I thought changing power would change current san or cap.  The implementation makes sense, sorry for wasting your time!
