### ISSUE TITLE
Character Sheet Tabs intermittently disappear

### ISSUE THREAD

**Issue by E1GB** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#46]
The tabs on the sheet vanish and require a sheet default refresh to restore them.  No modules running.

**Comment by TheLastScrub** [comment]
Could you confirm what version of the system you are using, what version of Foundry, and what browser you are using?

If you are using the preview release, I would recommend you roll back to the current public release.

**Comment by E1GB** [comment]
Thank you for the response, systems:
Foundry: 0.8.9
Delta Green (Unofficial) 1.0.2
I have tested on Firefox 94.0.1, changing the POW on a sheet from 14->12->14 or scrolling to the bottom of the skills tab and back up again intermittently replicate the issue, I can't find a case that does it predictably.
I have tested on Chrome 96.0.4664.45 and have yet to have it happen.

thank you for your time
