### ISSUE TITLE
Rolling luck with modifiers isn't possible...?

### ISSUE THREAD

**Issue by hydrated12** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#47]
Right-clicking onto the "Roll Luck" option doesn't bring up the penalty/bonus menu while the agent's handbook sometimes mentions them with luck rolls. An example would be the Spending Illicit Cash optional rule at page 91 where it states "Make an Accounting roll or a Luck roll, player’s choice, at a −20% penalty for an Extreme expense."

**Comment by TheLastScrub** [comment]
For whatever reason I was never able to bind the right-click on the header buttons.  Perhaps it is possible, let me know if you've seen it done in a different system and I'll look at their implementation.  

But you **can** _shift + click_ to get the modify roll dialog for the _Roll Luck_ button.  So what you are after is currently doable,  just need to use the alternate way of triggering the roll dialog (note - shift + click works for everything else as well).
