### ISSUE TITLE
Ritual skill is visible to players even with SAN hidden, which makes it possible to know your current san.

### ISSUE THREAD

**Issue by hydrated12** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#48]
Title explains most of it, if the players do know how the ritual skill is calculated(in my case they do), they can easily subtract its score from 99 and get their current sanity. Would be neat to hide that score too, didn't find an option to do so in the settings.

**Comment by TheLastScrub** [comment]
@hydrated12  Sorry for the long delay on this one, but hopefully this should be fixed now with v1.0.3 of the system.
