### ISSUE TITLE
Empty space in the character sheets and some problems with the display of windows.

### ISSUE THREAD

**Issue by Milkhare** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#50]
Hi! When upgrading to the latest version of Foundry 9.245, I had some problems. There was a lot of empty space in the character sheets, which is a little annoying. I also have problems with displaying the combat tracker window (if you right-click on it) and the macro window.
![2022-02-02 09_45_39-testtt • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/82135041/152094552-e04113fd-86cc-4f67-8362-2a516db96640.png)
![2022-02-02 09_45_31-testtt • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/82135041/152094557-ade78e50-537d-4775-aa0d-fc74eb5265ff.png)
![2022-02-02 09_45_23-testtt • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/82135041/152094558-cb276ab1-93e8-405a-b677-6aca8b2fb1c2.png)
![2022-02-02 09_45_17-testtt • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/82135041/152094559-2f823c86-c3d7-4a0a-8ec0-6b8b662a3650.png)
![2022-02-02 09_45_10-testtt • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/82135041/152094561-7fb41f9d-b83f-491c-801e-112214f6eecf.png)
![2022-02-02 09_45_02-testtt • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/82135041/152094564-c968cee2-1ff6-484b-aa9a-9f5d13d0076e.png)
![2022-02-02 09_28_52-testtt • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/82135041/152094566-2bd800d6-3006-4a62-b380-028d14f622f9.png)
![2022-02-02 09_27_56-testtt • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/82135041/152094567-0f6ac9f3-3c4a-462d-a38f-f2068609e7c1.png)

**Comment by TheLastScrub** [comment]
Thanks for the report.  I'm not too sure what you mean about the combat tracker and macro window, those seems to work okay for me at least in the latest version.  Perhaps you have a module that is interfering with those?

But I do see the gap in the Agent sheet that you mention. At a glance, I can't see any reason it would do that however...  When I have some time I will dig in and try to see why the tab sections for the nav are anchored to the bottom of the window rather than the bottom of the nav...

**Comment by Morfedel** [comment]
> Thanks for the report. I'm not too sure what you mean about the combat tracker and macro window, those seems to work okay for me at least in the latest version. Perhaps you have a module that is interfering with those?
> 
> But I do see the gap in the Agent sheet that you mention. At a glance, I can't see any reason it would do that however... When I have some time I will dig in and try to see why the tab sections for the nav are anchored to the bottom of the window rather than the bottom of the nav...

Hey Scrub, sorry to intrude on this conversation, new to Github and unfamiliar with how it works. 

Was trying to get in touch with you to find out if you are maintaining this? There are two games I was wanting to have supported in Foundry that isn't anywhere else, and this is one of them. 

I got my answer from the other game, so if you are supporting it on this one, I'll be picking up Foundry.

**Comment by TheLastScrub** [comment]
@Morfedel this is probably not the right place for this discussion, but in general while I am not a very active dev I don't plan on abandoning the project either (unless someone made a better alternative or something). I just would caution that it often takes me weeks or months to update the system when a new version of Foundry rolls out that has breaking changes.

**Comment by TheLastScrub** [comment]
@Milkhare I checked in a fix that seemed to correct the issue with the actor sheets, at least for me.  

I realize now what you probably meant by the Encounter Tracker and Macro editor is just that the font/background image makes it hard to read?  I will think on that, it might be a bit harder to fix.

**Comment by Morfedel** [comment]
> @Morfedel this is probably not the right place for this discussion, but in general while I am not a very active dev I don't plan on abandoning the project either (unless someone made a better alternative or something). I just would caution that it often takes me weeks or months to update the system when a new version of Foundry rolls out that has breaking changes.

I realize that, but I couldnt figure out how else to communicate with you. Sorry.

**Comment by TheLastScrub** [comment]
@Milkhare I think the fix was easier than I thought, I released another version that hopefully prevents most of the core Foundry windows from getting the custom background image that appears on the Actor Sheets.
