### ISSUE TITLE
INT as a weapon skill

### ISSUE THREAD

**Issue by razage** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#53]
One of the published modules (Jack Frost) includes a weapon that uses INT as its skill. While it is a niche case, it would be nice to be able to have all situations covered by this.

**Comment by TheLastScrub** [comment]
Interesting.  I will add it as an option, it is an easy change I think.

**Comment by TheLastScrub** [comment]
This change should have been made now in version 1.0.5.

![image](https://user-images.githubusercontent.com/67403321/159188999-aec080be-cedb-4548-ad0e-a21537c16290.png)
