### ISSUE TITLE
Feature request vehicle actor sheet

### ISSUE THREAD

**Issue by sedgetone** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#56]
Would it be possible to get a vehicle actor sheet please? I've had a number of occasions where the agents have been involved in car chases and would like a way vehicle sheets in Foundry.

**Comment by TheLastScrub** [comment]
Yeah, this is definitely doable. Might take me a little while to get around to it however, things are a bit busy for me right now. I may also choose to wait until Foundry v10 comes out, just so I have less that needs updated to the latest document model once the new changes in v10 are published.

**Comment by TheLastScrub** [comment]
Should be resolved with v1.1.0.
