### ISSUE TITLE
Character Sheet Backgrounds

### ISSUE THREAD

**Issue by thecodex101** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#57]
Hi, the backgrounds don't seem to change for the character sheets in the system settings. Backgrounds do, seems like default parchment is the only one that works.

**Comment by TheLastScrub** [comment]
I'm not sure I exactly follow, could you post a screenshot of what you are seeing?

Also, could you note what version of the Delta Green System and what version of Foundry VTT you are using?

**Comment by thecodex101** [comment]
Hi sorry for the delay. 

![image](https://user-images.githubusercontent.com/76156338/181842085-a66e9a16-877a-4db0-a5cf-8c0da0e8557a.png)

If I change the background options nothing happen on the character sheets...

using version Foundry v9 build269 & DG 1.0.6

**Comment by TheLastScrub** [comment]
Note when you change the setting, you need to refresh the browser for the change to take effect.  I'm using the same version of Foundry and DG as you, and it seems to work for me... What browser are you using? If you hit F12 to view the console, do you see any errors?

Here's what it looks like on my end after changing the settings and hitting refresh:

![image](https://user-images.githubusercontent.com/67403321/181876125-cd167151-f9e9-4232-b2f9-2550892ccec4.png)

![image](https://user-images.githubusercontent.com/67403321/181876158-05c290a6-ce02-436b-9099-1a776847c277.png)

![image](https://user-images.githubusercontent.com/67403321/181876182-141ae080-6c7d-4c26-9001-f1ebdad09b8a.png)

**Comment by TheLastScrub** [comment]
Going to go ahead and close this for now, but feel free to open another issue if it's still a problem.
