### ISSUE TITLE
Corruption values should be hidden for Agents

### ISSUE THREAD

**Issue by muckaluck1** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#59]
I'd love to track my Agent's Corruption but per the Impossible Landscapes book 

"Maintain a Corruption rating for each Agent, from 0 to 10.  Make sure players never know their scores or that you are tracking them. Keep the Corruption rating itself unknown if you can."

So can this section be hidden to players?

**Comment by TheLastScrub** [comment]
Is it not? Only someone logged in with GM level privileges should be able to see it. Try logging in as one of your players and see if you can still see the field.

**Comment by TheLastScrub** [comment]
Going to go ahead and close this, feel free to re-open if it's still an issue.
