### ISSUE TITLE
Bug: x5 showing for weapon skill rolls

### ISSUE THREAD

**Issue by jalensailin** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#62]
![image](https://user-images.githubusercontent.com/72114365/187829005-29764aac-bb21-4aff-ad10-b5a91899a8db.png)

We see that it says "Melee Weapons**x5**" when this uses a skill, not a stat. I can try to tackle this but just wanted to document it

**Comment by TheLastScrub** [comment]
Should be resolved with v1.1.0.
