### ISSUE TITLE
Modifiers Built into Weapons 

### ISSUE THREAD

**Issue by pvt900** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#72]
Could we get the ability to define modifiers to be added to rolls automatically if I define something in the item's settings? Like explosives and modded weapons that gain varying %s. Could help improve the flow of game of being able to define that the explosive has a bonus and then clicking it for the roll rather than recalling to right-click it to add it.

**Comment by TheLastScrub** [comment]
Better late than never? This should be added in v1.3.0
