### ISSUE TITLE
Portuguese translation does not display.

### ISSUE THREAD

**Issue by jalensailin** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#74]
Apparently the Portuguese translation doesn't work for some reason.

Steps to test:

1. Create world and set language to Spanish.
2. Refresh and see that delta-green strings are correctly in Spanish (on actor sheets, item sheets, etc)
3. Set language to Portuguese and refresh.
4. Note that strings are not translated.

**Comment by TheLastScrub** [comment]
There are two 'Portuguese (Brazil)' options in the Foundry list. I do not know why. But the first one (highlighted blue) does not work, but the second one (highlighted yellow) does work for me.

<img width="475" alt="image" src="https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/67403321/7de5e416-ad1e-4d4a-9557-1d71baa8fb3c">

**Comment by jalensailin** [comment]
This should be fixed in the current master.
