### ISSUE TITLE
Official Material for Foundry VTT

### ISSUE THREAD

**Issue by michaelericbrown** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#77]
Hi TheLastScrub,

I'm working with Shane Ivey at Arc Dream Publishing to begin offering official _Delta Green_ content on Foundry VTT. Having seen your work on the unofficial _Delta Green_ Game System, he has asked me to send you his email so that you two can connect: you can reach him via shane@arcdream.com.

Speaking of your implementation of the _Delta Green_ Game System, there were a few items we'd love to tweak:

1. Under Items, it would be awesome if that Expense dropdown had an option to select something like N/A or None. This would be appropriate for items discovered by the Agents during their investigation, as opposed to the kinds of items they can requisition.
2. Under the character sheet, it would be best to use the official designations for the tabs: Statistics rather than Physical, Psychological rather than Mental, Equipment rather than Gear, Personal rather than C.V., and Bonds rather than Contacts.
3. Also on the character sheet, under the ? tab, Shane said that all you need is the paragraph that begins "Published by arrangement with the Delta Green Partnership." The references the license file and the note about the Open Game License can go. (Going forward, Arc Dream Publishing content will _not_ include anything OGL-related, given the controversy from earlier this year.)
4. On the NPC character sheet, please change Sanity Damage to just SAN to match the official stat block.

We both look forward to hearing from you.

Thank you!

Michael

**Comment by TheLastScrub** [comment]
Hey Michael, I will reach out to Shane. I think we exchanged some correspondence when I first started working on the system.

#1, #2 and #4 are all pretty easy. I can make those changes fairly quickly.

#3

The OGL reference is an oversight, I had already removed the OGL license file from the code after that whole kerfluffle, I will clean up that remaining text as well. 

But I am a little hesitant to remove the license.txt file, as the code for the system itself is supposed to be under the MIT license. What is the reason for removing the open source license for the system? Is it ambiguous what is covered under the MIT license and what is under the DG partnership clause?  

Also, should I remove the line that says "This is an unofficial fan work, it is not affiliated with or endorsed by Shane Ivey or Arc Dream Publishing" or leave that part in?

**Comment by michaelericbrown** [comment]
My mistake on the MIT license. I mistook that as being a reference for the Delta Green Partnership. Let's leave that in.

As for the line saying that it's an unofficial fan work, I'm going to say let's check with Shane on that first.

**Comment by TheLastScrub** [comment]
Resolved in v1.2.3
