### ISSUE TITLE
Allow Toggling How SAN is Treated for an NPC (Agent-like, or Unnatural-like)

### ISSUE THREAD

**Issue by TheLastScrub** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#79]
Requested by @michaelericbrown, allow toggling NPC sheet's handling of SAN, such that they can have sanity loss like an Agent, or inflict sanity damage like the unnatural.

![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/67403321/c205137f-4270-4c67-b622-45c9f54f0857)

**Comment by jalensailin** [comment]
Aren't NPCs and Unnaturals two different actor types? So basically the behavior could just depend on what `actor.type` is

**Comment by michaelericbrown** [comment]
You could make another actor type and call it Unnatural. However, you would still want to include all of the other elements from the existing NPC character sheet, including the six core stats. For example, That Which Was Marlene (Last Things Last) has a CHA stat, even though that is rare for an entity.

**Comment by TheLastScrub** [comment]
@michaelericbrown There is already an “unnatural” actor type, and it has SAN damage rather than remaining SAN like an agent. The unnatural actor is meant for things like marlene, whereas I meant the “npc” actor type is really more for human NPCs.

I assumed you wanted the NPC sheet to be more flexible, but you might check the unnatural character sheet to see if it does what you want already. It’s not that hard to add to the NPC sheet though. 

Note you can’t currently roll SAN damage off the unnatural sheet. But I have that working in my test setup.

**Comment by michaelericbrown** [comment]
@TheLastScrub I had actually used the Unnatural actor type when creating That Which Was Marlene for the _Need to Know_ module, but I had forgotten that was an option in the time since I finished it. Accordingly, @jalensailin's suggestion makes complete sense to me. A toggle would be unnecessary.

**Comment by TheLastScrub** [comment]
Closing since no longer required.
