### ISSUE TITLE
Hide Sanity from players not working correctly

### ISSUE THREAD

**Issue by mredaniels** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#87]
Players can see their Sanity score/target when rolling sanity.  And when they shift click to toggle to blind gm (or whatever), it can be seen.  And there is no option anywhere to make all Sanity rolls private/blind rolls

**Comment by jalensailin** [comment]
my bad on that! one of those things i forgot to check when redoing rolls. should be fixed soon

**Comment by jalensailin** [comment]
I am able to replicate the first issue you brought up but not the second.

This is what I see as a player when I shift-click to roll sanity: 

![image](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/72114365/97b44a0c-6a1c-475f-aff7-ced4081c5983)

**Comment by TheLastScrub** [comment]
Should be fixed in latest (v.1.3.2), feel free to re-open the issue if not. 

I don't think we ever reproduced the issue in the roll modifier dialogue, but the System-specific option to hide SAN should be working again as it was prior to the roll refactor in v.1.3.0.
