### ISSUE TITLE
Custom attack target field does not commit value

### ISSUE THREAD

**Issue by jakefurb** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#93]
Hi. First off, thank you so much for all the work you've done on the Delta Green mod. It's excellent work, and we're really enjoying it. I hope this is the appropriate place to report what I think may be a bug.

When adding unnatural Actors, using the Skill "Custom" value in an Attack record makes the "Target" field visible. The system does not appear to commit a value in that field (any value entered in the field is wiped as soon as you leave it), such that all attack rolls using the "Custom" Skill value have a Target value of zero.

**Comment by TheLastScrub** [comment]
Thanks for the report, this is the right place to report it. Kind of an odd one but I think I see how to fix it.

**Comment by jalensailin** [comment]
Have a fix incoming! Probably can get to opening the PR tonight

**Comment by jakefurb** [comment]
Dang, that was fast! Thanks for your attention to this!

**Comment by jalensailin** [comment]
Of course! Thanks for bringing it to our attention

**Comment by TheLastScrub** [comment]
Should be fixed in v.1.3.3 that @jalensailin released today.
